--------------------------------------------------------
--  파일이 생성됨 - 토요일-2월-10-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT_PAYMENT
--------------------------------------------------------

  CREATE TABLE "GOODS"."PRODUCT_PAYMENT" 
   (	"PAYMENT_ID" NUMBER, 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"PRD_ID" VARCHAR2(20 BYTE), 
	"BUY_QUANTITY" NUMBER, 
	"MEMBER_ZIPCODE" VARCHAR2(20 BYTE), 
	"MEMBER_FADDR" VARCHAR2(350 BYTE), 
	"MEMBER_LADDR" VARCHAR2(350 BYTE), 
	"MEMBER_PHONE" VARCHAR2(20 BYTE), 
	"CREDIT_NUMBER" VARCHAR2(20 BYTE), 
	"PAYMENT_DATE" DATE DEFAULT SYSDATE, 
	"PRD_OPT" VARCHAR2(20 BYTE), 
	"DELIVERY" VARCHAR2(20 BYTE), 
	"PRD_SUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into GOODS.PRODUCT_PAYMENT
SET DEFINE OFF;
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (165,'test','3',0,'04522','서울 중구 남대문로 109(다동, 국제빌딩)','test','010-1-1','3-3-3-3',to_date('22/10/03','RR/MM/DD'),null,null,130000);
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (164,'test','4',0,'04522','서울 중구 남대문로 109(다동, 국제빌딩)','test','010-1-1','4-4-4-4',to_date('22/10/03','RR/MM/DD'),null,null,null);
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (164,'test44','3',0,'05237','서울 강동구 아리수로 46(암사동)','dd','010-3333-3333','4-4-4-4',to_date('22/10/11','RR/MM/DD'),'완전자차',null,130000);
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (165,'test','25',0,'04522','서울 중구 남대문로 109(다동, 국제빌딩)','test','010-1111-1111','1-1-1-1',to_date('22/10/11','RR/MM/DD'),'완전자차',null,230000);
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (166,'test','13',0,'04522','서울 중구 남대문로 109(다동, 국제빌딩)','test','010-1111-1111','1-1-1-1',to_date('22/10/11','RR/MM/DD'),'완전자차',null,170000);
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (167,'test33','3',0,'05237','서울 강동구 아리수로 46(암사동)','dd','010-3333-3333','3-3-3-3',to_date('22/10/11','RR/MM/DD'),'완전자차',null,130000);
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (168,'test55','3',0,'57638','전남 구례군 구례읍 5일시장작은길 3(봉동리)','55','010-5555-5555','5-5-5-5',to_date('22/10/11','RR/MM/DD'),'완전자차',null,130000);
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (181,'a','25',1,'46760','부산 강서구 르노삼성대로 14(신호동)','3','010-3-3','3-3-3-3',to_date('23/03/31','RR/MM/DD'),'완전자차',null,230000);
Insert into GOODS.PRODUCT_PAYMENT (PAYMENT_ID,MEMBER_ID,PRD_ID,BUY_QUANTITY,MEMBER_ZIPCODE,MEMBER_FADDR,MEMBER_LADDR,MEMBER_PHONE,CREDIT_NUMBER,PAYMENT_DATE,PRD_OPT,DELIVERY,PRD_SUM) values (201,'test','25',1,'04522','서울 중구 남대문로 109(다동, 국제빌딩)','test','010-1111-1111','3-3-3-31',to_date('23/04/27','RR/MM/DD'),'일반자차1',null,630000);
--------------------------------------------------------
--  Constraints for Table PRODUCT_PAYMENT
--------------------------------------------------------

  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("PAYMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("CREDIT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("MEMBER_LADDR" NOT NULL ENABLE);
  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("MEMBER_FADDR" NOT NULL ENABLE);
  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("MEMBER_ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("BUY_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("PRD_ID" NOT NULL ENABLE);
  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "GOODS"."PRODUCT_PAYMENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
